### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by aleixsr** [TravisSpangle/redmine_spent_time_in_issue_description#17]
Hello,
currently date format is mm/dd/yyyy, it should be possible to change it to yyyy/mm/dd or dd/mm/yyyy?

Thank you very much

**Comment by Pierstoval** [comment]
:+1: Love this idea!

**Comment by TravisSpangle** [comment]
The date format now uses the Redmine settings. Please update and let me know if it works for you.

**Comment by Pierstoval** [comment]
Works for me :)

**Comment by aleixsr** [comment]
It works, thank you very much!
