### ISSUE TITLE
Please tag versions!

### ISSUE THREAD

**Issue by ippeiukai** [TravisSpangle/redmine_spent_time_in_issue_description#18]
I saw versions 2.6 (2015-03-12) and 2.5 (2015-02-24) listed on Plugins Directory but not in `git tag -l`.  

I install my plugins at their latest versions' tags to avoid accidents. Please tag versions!

**Comment by TravisSpangle** [comment]
Thanks for catching that and for the feed back you left. I saw you mention 'some glitches with setting page'. Could you provide more details?

**Comment by ippeiukai** [comment]
> I saw you mention 'some glitches with setting page'. Could you provide more details?

I'll try my best to remember what happened:
Basically the plugin installed smoothly; `git clone`, `git tag -l` (oot!), `git checkout master`, `rake redmine:plugins:migrate`, then restart daemon.
I think the first thing I noticed was that Time Entries did not show any columns. I went to the plugin setting and selected all the columns and clicked the submit button at the bottom. It never submitted anything. So, I resorted to using the javascript console to submit the form, and it worked.

My guess is something to do with jquery or on-submit handler. Could be caused by anything from Redmine version to compatibility with other plugins to be honest.

**Comment by TravisSpangle** [comment]
Sounds like two problems

* Default config didn't take
* The Settings uses JavaScript Validation. I wonder if that was your problem. 

I'll keep this issue open and try to reproduce your issues.

**Comment by ippeiukai** [comment]
> I'll keep this issue open and try to reproduce your issues.

Thanks. As I noted in the review, it's on a fairly old version of Redmine and could well be an isolated incident too. I wouldn't try too hard to reproduce it. 

I'll let you know if I can dig up any more details.

**Comment by TravisSpangle** [comment]
I corrected the syntax and the default columns now load. 

I won't bother reproducing your JS error. If you don't have JavaScript turned on or jQuery then the validation would not block the submission process.
