### ISSUE TITLE
Conflict with plugin "redmine_spent_time_required"

### ISSUE THREAD

**Issue by LeDistordu** [TravisSpangle/redmine_spent_time_in_issue_description#19]
https://github.com/TeamRocketScience/redmine_spent_time_required

WARNING: settings partial 'settings/spent_time_settings' is declared in 'redmine_spent_time_required' plugin but it is already used by plugin 'redmine_spent_time_in_issue_description'. Only one settings view will be used. You may want to contact those plugins authors to fix this.

**Comment by Pierstoval** [comment]
:+1: Thx for mentionning and issueing in both.
 
Let me just ping TeamRocketScience/redmine_spent_time_required#10 to allow both referencing

**Comment by TravisSpangle** [comment]
Thanks for reporting this. I'll try to have this resolved by the end of next week.

**Comment by TravisSpangle** [comment]
Hey I had some time today. Can you update from master and confirm if it's resolved?

**Comment by LeDistordu** [comment]
[ 2015-04-13 16:54:53.4388 15177/7f5bbffff700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 2-108680] Cannot checkout session because a spawning error occurred. The identifier of the error is 198f37b8. Please see earlier logs for details about the error.
[ 2015-04-13 16:54:53.4389 15177/7f5bbffff700 Ser/Server.h:931 ]: [Client 2-108680] Disconnecting client with error: client socket write error: Broken pipe (errno=32)
App 29601 stdout:
App 29601 stderr: [DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
App 29601 stderr:
2015/04/13 16:54:56 [info] 15198#0: *435963 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too (104: Connection reset by peer) while sending request to upstream, client: 172.16.3.2, server: localhost, request: "HEAD / HTTP/1.0", upstream: "passenger:unix:/tmp/passenger.bvIniIP/agents.s/server:"
App 29601 stdout:
[ 2015-04-13 16:54:57.5337 15177/7f5bbdf43700 App/Implementation.cpp:287 ]: Could not spawn process for application /var/redmine: An error occured while starting up the preloader.
  Error ID: f5e178ed
  Error details saved to: /tmp/passenger-error-tufCxU.html
  Message from application: Permission denied - /var/redmine/plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb (Errno::EACCES)
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/fileutils.rb:1381:in `initialize'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/fileutils.rb:1381:in `open'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/fileutils.rb:1381:in `block in copy_file'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/fileutils.rb:1380:in `open'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/fileutils.rb:1380:in `copy_file'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/fileutils.rb:477:in `copy_file'
  /var/redmine/plugins/redmine_spent_time_in_issue_description/lib/setup_issue_show.rb:29:in `replace'
  /var/redmine/plugins/redmine_spent_time_in_issue_description/init.rb:19:in `block (2 levels) in <top (required)>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:446:in `instance_exec'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:192:in `call'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:192:in `block in simple'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `block in call'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `each'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_prepare_callbacks'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:180:in `each'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
  /var/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:111:in `eval'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:111:in `preload_app'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:157:in `<module:App>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.0.0-p643/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:28:in `<main>'


[ 2015-04-13 16:54:57.5375 15177/7f5bc48fa700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 1-108681] Cannot checkout session because a spawning error occurred. The identifier of the error is f5e178ed. Please see earlier logs for details about the error.
[ 2015-04-13 16:54:57.5376 15177/7f5bc48fa700 Ser/Server.h:931 ]: [Client 1-108681] Disconnecting client with error: client socket write error: Broken pipe (errno=32)

**Comment by TravisSpangle** [comment]
LeDistordu that looks like an nginx error. Do you need to reset the permissions on the plugin so your server has access?

**Comment by TravisSpangle** [comment]
The original task for this issue has been completed so I'm closing it.  LeDistordu someone else has reported your issue. I think is happening because the plugin is trying to copy a file and isn't allowed to. Can you try providing permissions to modify files in the directory ./redmine_spent_time_in_issue_description/app/views/issues?

Please follow and update on #23

**Comment by LeDistordu** [comment]
It's ok for me ;) Thank you for this plugin and help !!
