### ISSUE TITLE
edit/delete button missing

### ISSUE THREAD

**Issue by mmiat** [TravisSpangle/redmine_spent_time_in_issue_description#21]
very useful plugin, great job!
please add edit and delete button in issue page, now I need to go to time_entries page and search issue I want do modify
thanks

**Comment by Pierstoval** [comment]
:+1:

**Comment by TravisSpangle** [comment]
Edit / Delete buttons have been added to the Issue Body Description. You can get them out of master now. I haven't found a design I like for the floating Time Spent report.

**Comment by mmiat** [comment]
great! thanks!
