### ISSUE TITLE
sometimes "Hours" are not shown

### ISSUE THREAD

**Issue by mmiat** [TravisSpangle/redmine_spent_time_in_issue_description#22]
Hi
strange behaviour:
I added "30m", it tranforms in "0.5" and I see "hours" under "description"
I addess "180m", it transforms in "3.0" and I see nothing in "hours"
![screenshot 2015-04-21 12 46 23](https://cloud.githubusercontent.com/assets/11910225/7250661/8a727662-e824-11e4-858e-33df6060387c.png)

**Comment by TravisSpangle** [comment]
Thank you for reporting this. I was able to reproduce this when using the humanized format for any time entry that had 0 minutes. Please update and confirm if it's now working as expected.

**Comment by mmiat** [comment]
yes, it's ok now!thanks




----Messaggio originale----

Da: notifications@github.com

Data: 23/04/2015 2.53

A: "TravisSpangle/redmine_spent_time_in_issue_description"<redmine_spent_time_in_issue_description@noreply.github.com>

Cc: "mmiat"<mmiat@libero.it>

Ogg: Re: [redmine_spent_time_in_issue_description] sometimes "Hours" are not shown (#22)




Thank you for reporting this. I was able to reproduce this when using the humanized format for any time entry that had 0 minutes. Please update and confirm if it's now working as expected.
