### ISSUE TITLE
Error loading views files?

### ISSUE THREAD

**Issue by GavinDonnelly** [TravisSpangle/redmine_spent_time_in_issue_description#23]
Hi,

I have just installed this plugin on a Linux redmine server, with a bitnami stack install. There is no errors when I rake the plugins but when I restart the server I get an errors in the views folder:

![image](https://cloud.githubusercontent.com/assets/12139488/7392333/3a9bde6a-ee7f-11e4-9c50-1b09cad52bd0.png)

It seems like a permissions error, but I cant really pin point what the fix would be here?

Any help would be appreciated.

**Comment by TravisSpangle** [comment]
This is happening because the plugin is trying to copy a file and isn't allowed to. Can you try providing permissions to modify files in the directory ./redmine_spent_time_in_issue_description/app/views/issues?

**Comment by GavinDonnelly** [comment]
Hi,

So I changed the file permssion on the files and directorys:
![image](https://cloud.githubusercontent.com/assets/12139488/7396711/3a63bbf4-ee9b-11e4-9155-d8ed8f67866a.png)

(I dont think the world should need permissions here)

 Still the same failure?

**Comment by TravisSpangle** [comment]
Is bitnami also the servers user? 

Until I can get the hooks installed in the views - http://www.redmine.org/issues/19188 - I am overwriting the Issue View. To make sure my view harmonizes with the Redmine view I have them broken out by Redmine versions, https://github.com/TravisSpangle/redmine_spent_time_in_issue_description/tree/master/app/views/issues. 

When the app loads up it identifies the Redmine version and copies the correct versioned file as show.html.erb. This is where your app ( and others ) are failing.  

---

I will implement a feature that does the copy file in a try-catch block. If it cannot perform the operation it will log it and default to the Redmine view.

**Comment by GavinDonnelly** [comment]
Yes this is a bitnami stack install, but the user is also bitnami. Okay that sounds like a good solution untill a fix is found.

**Comment by TravisSpangle** [comment]
The behavior is now implemented and deployed to 2.7. If the plugin is unable to copy the correct file over then it will report an error on the configuration settings page. It will inform the user what file needs to be copied over as show.html.erb.
