### ISSUE TITLE
Problem with Redmine 3.2.0

### ISSUE THREAD

**Issue by droyazri** [TravisSpangle/redmine_spent_time_in_issue_description#35]
Redmine 3.2.0-stable
Issue Description with Spent Time 2.8.0

Enabling the plugin "Issue Description with Spent Time" pushes the issue description and other fields to the bottom of the page. I tried various themes and plugin configurations which didn't help. 

Does anyone else have this issue?

![screenshot - 21 12 2015 16_41_03](https://cloud.githubusercontent.com/assets/16387185/11934563/57184cc0-a803-11e5-9bc2-9c76eabe4f30.png)
![screenshot - 21 12 2015 16_41_31](https://cloud.githubusercontent.com/assets/16387185/11934562/5714544e-a803-11e5-8b14-b9f36994c9a1.png)

**Comment by TravisSpangle** [comment]
I'm unable to reproduce this, do you have any other plugins or customizations?

**Comment by itsecureadmin** [comment]
We have also seen this issue after upgrading from 3.1 to 3.2 stable.  The issue went away when removing the redmine spent time in issue plugin.

    Environment:
      Redmine version                3.2.0.stable
      Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
      Rails version                  4.2.5
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Subversion                     1.8.13
     Git                            2.4.3
      Filesystem                     
    Redmine plugins:
      redmine_spent_time_in_issue_description 2.8.0

We are using the circle theme but I can reproduce the issue with the default theme.

We have a number of other plugins but I can reproduce the issue with all of them disabled with the exception of spent time in issue description.

**Comment by droyazri** [comment]
No customizations, but we use a few plugins. However, the issue is there whether I enable them or not. Here is the full list of plugins, just in case.

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  progressive_projects_list      2.0.1
  redcase                        1.0
  redmine_agile                  1.3.12
  redmine_ckeditor               1.1.2
  redmine_contacts               4.0.3
  redmine_contacts_helpdesk      3.0.1
  redmine_custom_workflows       0.1.6
  redmine_dashboard              2.7.0
  redmine_dmsf                   1.5.5
  redmine_lightbox2              0.2.4
  redmine_monitoring_controlling 0.1.1
  redmine_people                 1.1.0
  redmine_spent_time             3.1.2
  redmine_timesheet_plugin       0.7.0
  redmine_work_time              0.3.1

**Comment by nkgokul** [comment]
Facing the same issue. The issue is coming only for Redmine version 3.2.0.stable

As you can see from the image, the issue seems to be arising from %done and it seems to be a case of missing/additional div. I was not able to debug it.

I think adding a new view template in https://github.com/TravisSpangle/redmine_spent_time_in_issue_description/tree/master/app/views/issues for 3.2.0 version with the right format should fix this issue.

**Comment by TravisSpangle** [comment]
Thank you! I've added a 3.2.0 template. Can you checkout the 'feature/add-3.2.0' branch and verify if the issue is resolved?

**Comment by droyazri** [comment]
Thanks, that fixed it for us!

**Comment by TravisSpangle** [comment]
Thanks everyone!
