### ISSUE TITLE
Compatibility with Redmine 3.3

### ISSUE THREAD

**Issue by leguminator** [TravisSpangle/redmine_spent_time_in_issue_description#37]
Hello,
Can you tell if your plugin is already compatible with Redmine 3.3 ?
If not, are you planning to do so ?
Thanks

**Comment by TravisSpangle** [comment]
No, I am not planning on it. Have you experienced issues with 3.3?

**Comment by Pierstoval** [comment]
I'm using it with 3.3.0-stable and I have no issue
